Plug 'powerman/vim-plugin-viewdoc'
Plug 'ryanoasis/vim-devicons'
Plug 'powerline/powerline'
Plug 'simeji/winresizer'

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-jedi'
