Plug 'powerman/vim-plugin-viewdoc'
Plug 'ryanoasis/vim-devicons'
Plug 'powerline/powerline'
Plug 'simeji/winresizer'
Plug 'zhou13/vim-easyescape'

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-pyclang'
Plug 'ncm2/ncm2-jedi'
Plug 'ncm2/ncm2-ultisnips'
" snipmate dependencies
Plug 'tomtom/tlib_vim'
Plug 'marcweber/vim-addon-mw-utils'
Plug 'garbas/vim-snipmate'

Plug 'ncm2/ncm2-snipmate'
" Plug 'ncm2/ncm2-go'
Plug 'metalelf0/supertab'
